- type: latheRecipePack
  id: SecurityAmmoRatbiteDynamic
  recipes:
  - MagazineBox38MagnumIncendiary
  - MagazineBox38MagnumUranium
  - SpeedLoader38MagnumIncendiary
  - SpeedLoader38MagnumUranium 
  - EnergyMagPistolIon
  - EnergyMagPistolOverchargeLethal

- type: latheRecipePack
  id: SecurityAmmoRatbiteStatic
  recipes:
  - MagazineBox38Magnum
  - MagazineBox38MagnumPractice
  - SpeedLoader38MagnumEmpty
  - SpeedLoader38Magnum
  - SpeedLoader38MagnumPractice
  - EnergyMagPistolLethal
  - EnergyMagPistolDisabler