- type: latheRecipePack
  id: SecurityAmmoRatbiteDynamic
  recipes:
  - EnergyMagPistolIon
  - EnergyMagPistolOverchargeLethal

- type: latheRecipePack
  id: SecurityAmmoRatbiteStatic
  recipes:
  - EnergyMagPistolLethal
 # - EnergyMagPistolDisabler - Kill double disabler
